### ISSUE TITLE
Upload new release to crates.io

### ISSUE THREAD

**Issue by v0x0g** [not-fl3/egui-miniquad#70]
I'm using this crate as one of the available backends for my `egui` application, but I'm using a pretty modern version (`egui@0.27.2`). This isn't compatible with the latest release of `egui-miniquad@0.14.0` on crates-io, so I had to change my dependencies to point to the git repo that used the newer version, following #68.

```toml
# Patching `Cargo.toml`
[patch.crates-io]
egui_miniquad = { git = "ssh://git@github.com/not-fl3/egui-miniquad.git", branch = "master", package = "egui-miniquad" }
```

OR
```toml
# Overriding the dependency when I use it
[dependencies]
egui_miniquad = { git = "ssh://git@github.com/not-fl3/egui-miniquad.git", branch = "master", package = "egui-miniquad" }
```

This works fine for when I want to build and run the app, but I want to get it published to `crates.io`, which it won't let me do. Whenever I try `cargo package` or `cargo publish`, I get errors due to having dependencies that point to git repos, as opposed to crates on `crates.io` (see https://github.com/rust-lang/cargo/issues/6738#issuecomment-472224210, https://github.com/rust-lang/cargo/pull/7237#issuecomment-532283875). Essentially, I can't publish unless all my dependencies are also published (patching isn't allowed either).

Therefore, I'd like to ask if it's possible to upload a new release to `crates.io` (considering the last release was over a year ago). From looking at other issues #65 (https://github.com/not-fl3/egui-miniquad/pull/65#issuecomment-1955903463), it seems that `miniquad@0.4.0` is stable now, so this shouldn't be an issue to release a new version.
